# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.9'

    - name: Build
      run: mkdir artifact && cp -r wordnet-dist artifact && go build -o artifact/username-generator -v ./... && GOOS=windows GOARCH=amd64 go build -o artifact/username-generator.exe -v ./...
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: artifact
